//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackTimer.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackTimer.Core.Resources.CoreResources", typeof(CoreResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavily Modified.
        /// </summary>
        internal static string Enum_VehicleClass_HeavilyModified {
            get {
                return ResourceManager.GetString("Enum_VehicleClass_HeavilyModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightly Modified.
        /// </summary>
        internal static string Enum_VehicleClass_LightlyModified {
            get {
                return ResourceManager.GetString("Enum_VehicleClass_LightlyModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race Prepared.
        /// </summary>
        internal static string Enum_VehicleClass_RacePrepared {
            get {
                return ResourceManager.GetString("Enum_VehicleClass_RacePrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Enum_VehicleClass_Standard {
            get {
                return ResourceManager.GetString("Enum_VehicleClass_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        internal static string Text_Unit_Degrees {
            get {
                return ResourceManager.GetString("Text_Unit_Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string Text_Unit_DegreesCentigrade {
            get {
                return ResourceManager.GetString("Text_Unit_DegreesCentigrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F.
        /// </summary>
        internal static string Text_Unit_DegreesFarenheit {
            get {
                return ResourceManager.GetString("Text_Unit_DegreesFarenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string Text_Unit_Inches {
            get {
                return ResourceManager.GetString("Text_Unit_Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km/h.
        /// </summary>
        internal static string Text_Unit_KilometresPerHour {
            get {
                return ResourceManager.GetString("Text_Unit_KilometresPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPH.
        /// </summary>
        internal static string Text_Unit_MilesPerHour {
            get {
                return ResourceManager.GetString("Text_Unit_MilesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string Text_Unit_Millimetres {
            get {
                return ResourceManager.GetString("Text_Unit_Millimetres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Model.
        /// </summary>
        internal static string Text_Validation_Required_VehicleModel {
            get {
                return ResourceManager.GetString("Text_Validation_Required_VehicleModel", resourceCulture);
            }
        }
    }
}
