//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackTimer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackTimer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete track.
        /// </summary>
        public static string Text_ApplicationBar_DeleteTrack {
            get {
                return ResourceManager.GetString("Text_ApplicationBar_DeleteTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit track.
        /// </summary>
        public static string Text_ApplicationBar_EditTrack {
            get {
                return ResourceManager.GetString("Text_ApplicationBar_EditTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage friends.
        /// </summary>
        public static string Text_ApplicationBar_ManageFriends {
            get {
                return ResourceManager.GetString("Text_ApplicationBar_ManageFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string Text_ApplicationBar_Select {
            get {
                return ResourceManager.GetString("Text_ApplicationBar_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Text_ApplicationBar_Settings {
            get {
                return ResourceManager.GetString("Text_ApplicationBar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share track.
        /// </summary>
        public static string Text_ApplicationBar_ShareTrack {
            get {
                return ResourceManager.GetString("Text_ApplicationBar_ShareTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string Text_ApplicationBar_Upload {
            get {
                return ResourceManager.GetString("Text_ApplicationBar_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When your friends use Track Timer you will get updates here.
        /// </summary>
        public static string Text_Blurb_AddFriendsToSeeActivity {
            get {
                return ResourceManager.GetString("Text_Blurb_AddFriendsToSeeActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a sector, touch and hold the map at the sector location.
        /// </summary>
        public static string Text_Blurb_AddSector {
            get {
                return ResourceManager.GetString("Text_Blurb_AddSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        public static string Text_Blurb_BackgroundTransferComplete {
            get {
                return ResourceManager.GetString("Text_Blurb_BackgroundTransferComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error - tap to view.
        /// </summary>
        public static string Text_Blurb_BackgroundTransferError {
            get {
                return ResourceManager.GetString("Text_Blurb_BackgroundTransferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        public static string Text_Blurb_BackgroundTransferPaused {
            get {
                return ResourceManager.GetString("Text_Blurb_BackgroundTransferPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfering.
        /// </summary>
        public static string Text_Blurb_BackgroundTransferTransfering {
            get {
                return ResourceManager.GetString("Text_Blurb_BackgroundTransferTransfering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string Text_Blurb_BackgroundTransferUnknown {
            get {
                return ResourceManager.GetString("Text_Blurb_BackgroundTransferUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting.
        /// </summary>
        public static string Text_Blurb_BackgroundTransferWaiting {
            get {
                return ResourceManager.GetString("Text_Blurb_BackgroundTransferWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting for external power.
        /// </summary>
        public static string Text_Blurb_BackgroundTransferWaitingForExternalPower {
            get {
                return ResourceManager.GetString("Text_Blurb_BackgroundTransferWaitingForExternalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting for external power due to Battery Save mode.
        /// </summary>
        public static string Text_Blurb_BackgroundTransferWaitingForExternalPowerDueToBatterySaverMode {
            get {
                return ResourceManager.GetString("Text_Blurb_BackgroundTransferWaitingForExternalPowerDueToBatterySaverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting for non voice blocking network.
        /// </summary>
        public static string Text_Blurb_BackgroundTransferWaitingForNonVoiceBlockingNetwork {
            get {
                return ResourceManager.GetString("Text_Blurb_BackgroundTransferWaitingForNonVoiceBlockingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting for Wifi.
        /// </summary>
        public static string Text_Blurb_BackgroundTransferWaitingForWifi {
            get {
                return ResourceManager.GetString("Text_Blurb_BackgroundTransferWaitingForWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more Bluetooth GPS devices from the list of paired Bluetooth devices and the first available device will be used to track your lap progress. If none are selected then the internal GPS will be used..
        /// </summary>
        public static string Text_Blurb_BluetoothDeviceSelection {
            get {
                return ResourceManager.GetString("Text_Blurb_BluetoothDeviceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using an external GPS receiver requires Bluetooth to be enabled and the GPS reciever to be paired. You can enabled Bluetooth and pair the GPS receiver in your phones Bluetooth Settings..
        /// </summary>
        public static string Text_Blurb_BluetoothDisabled {
            get {
                return ResourceManager.GetString("Text_Blurb_BluetoothDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera test successful! Please verify that your camera is now off and has recording a short video clip..
        /// </summary>
        public static string Text_Blurb_Camera_TestSuccessfulPleaseVerifyYourCameraRecordedAShortClip {
            get {
                return ResourceManager.GetString("Text_Blurb_Camera_TestSuccessfulPleaseVerifyYourCameraRecordedAShortClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Timer can start and stop your Wifi enabled GoPro camera when timing starts. Your phone must be manually connected to the GoPro&apos;s WiFi network before timing starts..
        /// </summary>
        public static string Text_Blurb_CameraSetup {
            get {
                return ResourceManager.GetString("Text_Blurb_CameraSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop timing?.
        /// </summary>
        public static string Text_Blurb_CancelTimingPrompt {
            get {
                return ResourceManager.GetString("Text_Blurb_CancelTimingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sessions stored on your phone, including any sessions not uploaded to OneDrive, will be deleted. Are you sure you want to delete all local sessions?.
        /// </summary>
        public static string Text_Blurb_DeleteAllLocalSessionsPrompt {
            get {
                return ResourceManager.GetString("Text_Blurb_DeleteAllLocalSessionsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session will be permanently deleted. Are you sure you want to delete this session?.
        /// </summary>
        public static string Text_Blurb_DeleteSessionPrompt {
            get {
                return ResourceManager.GetString("Text_Blurb_DeleteSessionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tracks stored on your phone, including tracks not uploaded to the server and all custom track backgrounds, will be deleted. Are you sure you want to delete the local track cache?.
        /// </summary>
        public static string Text_Blurb_DeleteTrackCachePrompt {
            get {
                return ResourceManager.GetString("Text_Blurb_DeleteTrackCachePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This track and all associated sessions will be permanently deleted from your phone. To save sessions ensure they are uploaded to OneDrive before deleting this track. Are you sure you want to delete this track?.
        /// </summary>
        public static string Text_Blurb_DeleteTrackPrompt {
            get {
                return ResourceManager.GetString("Text_Blurb_DeleteTrackPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to access this feature please upgrade to the full version.
        /// </summary>
        public static string Text_Blurb_FeatureUnavailableInTrial {
            get {
                return ResourceManager.GetString("Text_Blurb_FeatureUnavailableInTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incomplete.
        /// </summary>
        public static string Text_Blurb_Incomplete {
            get {
                return ResourceManager.GetString("Text_Blurb_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Timer was closed before your last session was uploaded to OneDrive. You can upload this session manually via the Session Detail page..
        /// </summary>
        public static string Text_Blurb_IncompleteSessionSavePrompt {
            get {
                return ResourceManager.GetString("Text_Blurb_IncompleteSessionSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app accesses your phone&apos;s location. Is that ok?.
        /// </summary>
        public static string Text_Blurb_LocationPrompt {
            get {
                return ResourceManager.GetString("Text_Blurb_LocationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is disabled in phone settings. Please enable it to allow GPS lap timing..
        /// </summary>
        public static string Text_Blurb_LocationServicesSwitchedOff {
            get {
                return ResourceManager.GetString("Text_Blurb_LocationServicesSwitchedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access all the features of Track Timer you must sign in with Microsoft account. Would you like to log in now?.
        /// </summary>
        public static string Text_Blurb_MustAuthenticatePrompt {
            get {
                return ResourceManager.GetString("Text_Blurb_MustAuthenticatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Text_Blurb_New {
            get {
                return ResourceManager.GetString("Text_Blurb_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no leaderboard for this track yet. Set the pace!.
        /// </summary>
        public static string Text_Blurb_NoLeaderboard {
            get {
                return ResourceManager.GetString("Text_Blurb_NoLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timing to create your first session!.
        /// </summary>
        public static string Text_Blurb_NoSessions {
            get {
                return ResourceManager.GetString("Text_Blurb_NoSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to be an official lap it must meet the minimum length of.
        /// </summary>
        public static string Text_Blurb_OfficialLength {
            get {
                return ResourceManager.GetString("Text_Blurb_OfficialLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow your profile to be seen by all other users, e.g. your name shown against your best laps on the leaderboard.
        /// </summary>
        public static string Text_Blurb_PublicProfile {
            get {
                return ResourceManager.GetString("Text_Blurb_PublicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Windows 10 version of Track Timer is coming! If you would like to register to have your data migrated please select &apos;Ok&apos; and allow access to your email address. If you choose to &apos;Cancel&apos; you can still register later from the Settings -&gt; Support page..
        /// </summary>
        public static string Text_Blurb_RequestUpgradeRegistration {
            get {
                return ResourceManager.GetString("Text_Blurb_RequestUpgradeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish Line.
        /// </summary>
        public static string Text_Blurb_StartFinishLine {
            get {
                return ResourceManager.GetString("Text_Blurb_StartFinishLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap here to add a friend.
        /// </summary>
        public static string Text_Blurb_TapHereToAddAFriend {
            get {
                return ResourceManager.GetString("Text_Blurb_TapHereToAddAFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trial.
        /// </summary>
        public static string Text_Blurb_Trial {
            get {
                return ResourceManager.GetString("Text_Blurb_Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t find a track near your current location. You can edit the track details at the bottom of this page and when you start timing we&apos;ll try to figure out your laps..
        /// </summary>
        public static string Text_Blurb_UnknownTrackDescription {
            get {
                return ResourceManager.GetString("Text_Blurb_UnknownTrackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are registered for Track Timer for Windows 10 and you will be notified when it is available.
        /// </summary>
        public static string Text_Blurb_UpgradeRegistered {
            get {
                return ResourceManager.GetString("Text_Blurb_UpgradeRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Windows 10 version of Track Timer is coming! To have your existing Track Timer data migrated to the new version please register your interest below and allow Track Timer to access your email address..
        /// </summary>
        public static string Text_Blurb_UpgradeRegistration {
            get {
                return ResourceManager.GetString("Text_Blurb_UpgradeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weather data powered by.
        /// </summary>
        public static string Text_Blurb_WeatherDataCredit {
            get {
                return ResourceManager.GetString("Text_Blurb_WeatherDataCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicle.
        /// </summary>
        public static string Text_Buton_Vehicle {
            get {
                return ResourceManager.GetString("Text_Buton_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add friend.
        /// </summary>
        public static string Text_Button_AddFriend {
            get {
                return ResourceManager.GetString("Text_Button_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new vehicle.
        /// </summary>
        public static string Text_Button_AddNewVehicle {
            get {
                return ResourceManager.GetString("Text_Button_AddNewVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Text_Button_AddVehicle {
            get {
                return ResourceManager.GetString("Text_Button_AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth settings.
        /// </summary>
        public static string Text_Button_BluetoothSettings {
            get {
                return ResourceManager.GetString("Text_Button_BluetoothSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Text_Button_Cancel {
            get {
                return ResourceManager.GetString("Text_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose background.
        /// </summary>
        public static string Text_Button_ChooseBackground {
            get {
                return ResourceManager.GetString("Text_Button_ChooseBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact support or request a track.
        /// </summary>
        public static string Text_Button_ContactSupport {
            get {
                return ResourceManager.GetString("Text_Button_ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string Text_Button_Done {
            get {
                return ResourceManager.GetString("Text_Button_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Text_Button_EditVehicle {
            get {
                return ResourceManager.GetString("Text_Button_EditVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string Text_Button_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Text_Button_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase.
        /// </summary>
        public static string Text_Button_Purchase {
            get {
                return ResourceManager.GetString("Text_Button_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recalculate line.
        /// </summary>
        public static string Text_Button_RecalculateSectorLine {
            get {
                return ResourceManager.GetString("Text_Button_RecalculateSectorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register for upgrade.
        /// </summary>
        public static string Text_Button_RegisterForUpgrade {
            get {
                return ResourceManager.GetString("Text_Button_RegisterForUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete local sessions.
        /// </summary>
        public static string Text_Button_ResetSessions {
            get {
                return ResourceManager.GetString("Text_Button_ResetSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset track cache.
        /// </summary>
        public static string Text_Button_ResetTrackCache {
            get {
                return ResourceManager.GetString("Text_Button_ResetTrackCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revert to defaults.
        /// </summary>
        public static string Text_Button_RevertToDefaults {
            get {
                return ResourceManager.GetString("Text_Button_RevertToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review app.
        /// </summary>
        public static string Text_Button_ReviewApp {
            get {
                return ResourceManager.GetString("Text_Button_ReviewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Text_Button_Save {
            get {
                return ResourceManager.GetString("Text_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Text_Button_SaveVehicle {
            get {
                return ResourceManager.GetString("Text_Button_SaveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Text_Button_SignIn {
            get {
                return ResourceManager.GetString("Text_Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Text_Button_SignOut {
            get {
                return ResourceManager.GetString("Text_Button_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start timing.
        /// </summary>
        public static string Text_Button_StartTiming {
            get {
                return ResourceManager.GetString("Text_Button_StartTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms of use.
        /// </summary>
        public static string Text_Button_TermsOfUse {
            get {
                return ResourceManager.GetString("Text_Button_TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test camera.
        /// </summary>
        public static string Text_Button_TestCamera {
            get {
                return ResourceManager.GetString("Text_Button_TestCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        public static string Text_Button_Track {
            get {
                return ResourceManager.GetString("Text_Button_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploads....
        /// </summary>
        public static string Text_Button_Uploads {
            get {
                return ResourceManager.GetString("Text_Button_Uploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi settings.
        /// </summary>
        public static string Text_Button_WiFiSettings {
            get {
                return ResourceManager.GetString("Text_Button_WiFiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string Text_ContextMenu_AcceptFriend {
            get {
                return ResourceManager.GetString("Text_ContextMenu_AcceptFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de-friend.
        /// </summary>
        public static string Text_ContextMenu_DeleteFriend {
            get {
                return ResourceManager.GetString("Text_ContextMenu_DeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete sector.
        /// </summary>
        public static string Text_ContextMenu_DeleteSector {
            get {
                return ResourceManager.GetString("Text_ContextMenu_DeleteSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete vehicle.
        /// </summary>
        public static string Text_ContextMenu_DeleteVehicle {
            get {
                return ResourceManager.GetString("Text_ContextMenu_DeleteVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reject.
        /// </summary>
        public static string Text_ContextMenu_RejectFriend {
            get {
                return ResourceManager.GetString("Text_ContextMenu_RejectFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request friend.
        /// </summary>
        public static string Text_ContextMenu_RequestFriend {
            get {
                return ResourceManager.GetString("Text_ContextMenu_RequestFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not saved.
        /// </summary>
        public static string Text_DataSource_InMemory {
            get {
                return ResourceManager.GetString("Text_DataSource_InMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        public static string Text_DataSource_Local {
            get {
                return ResourceManager.GetString("Text_DataSource_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive*.
        /// </summary>
        public static string Text_DataSource_LocalAndOneDrive {
            get {
                return ResourceManager.GetString("Text_DataSource_LocalAndOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive.
        /// </summary>
        public static string Text_DataSource_SkyDrive {
            get {
                return ResourceManager.GetString("Text_DataSource_SkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inactive.
        /// </summary>
        public static string Text_Default_Inactive {
            get {
                return ResourceManager.GetString("Text_Default_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading.
        /// </summary>
        public static string Text_Default_Loading {
            get {
                return ResourceManager.GetString("Text_Default_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby.
        /// </summary>
        public static string Text_Default_Nearby {
            get {
                return ResourceManager.GetString("Text_Default_Nearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Text_Default_New {
            get {
                return ResourceManager.GetString("Text_Default_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Text_Default_NotApplicable {
            get {
                return ResourceManager.GetString("Text_Default_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        public static string Text_Default_NoValue {
            get {
                return ResourceManager.GetString("Text_Default_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending.
        /// </summary>
        public static string Text_Default_Pending {
            get {
                return ResourceManager.GetString("Text_Default_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Text_Default_UnknownCountry {
            get {
                return ResourceManager.GetString("Text_Default_UnknownCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown vehicle.
        /// </summary>
        public static string Text_Default_UnknownVehicle {
            get {
                return ResourceManager.GetString("Text_Default_UnknownVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your best lap time for this circuit could not be verified and will not be uploaded to the server.
        /// </summary>
        public static string Text_Error_BestLapTimeCouldNotBeVerified {
            get {
                return ResourceManager.GetString("Text_Error_BestLapTimeCouldNotBeVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to power off camera. Please verify that your camera has turned on and your phone is connected to the cameras WiFi network..
        /// </summary>
        public static string Text_Error_Camera_UnableToPowerOff {
            get {
                return ResourceManager.GetString("Text_Error_Camera_UnableToPowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to power on camera. Please verify that the password is correct and your phone is connected to the cameras WiFi network..
        /// </summary>
        public static string Text_Error_Camera_UnableToPowerOn {
            get {
                return ResourceManager.GetString("Text_Error_Camera_UnableToPowerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start recording. Please verify that your camera has turned on and your phone is connected to the cameras WiFi network..
        /// </summary>
        public static string Text_Error_Camera_UnableToStartRecording {
            get {
                return ResourceManager.GetString("Text_Error_Camera_UnableToStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to stop recording. Please verify that your camera has turned on and your phone is connected to the cameras WiFi network..
        /// </summary>
        public static string Text_Error_Camera_UnableToStopRecording {
            get {
                return ResourceManager.GetString("Text_Error_Camera_UnableToStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred:\n.
        /// </summary>
        public static string Text_Error_TheFollowingErrorsOccurred {
            get {
                return ResourceManager.GetString("Text_Error_TheFollowingErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error communicating with your GPS device. Ensure your device is compliant with the NMEA standard. If this occurs again please contact support with Error ID: {0}.
        /// </summary>
        public static string Text_Error_UnableToCommunicateWithExternalGpsDevice {
            get {
                return ResourceManager.GetString("Text_Error_UnableToCommunicateWithExternalGpsDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error communicating with your devices GPS provider. If this occurs again please contact support with Error ID: {0}.
        /// </summary>
        public static string Text_Error_UnableToCommunicateWithInternalGpsDevice {
            get {
                return ResourceManager.GetString("Text_Error_UnableToCommunicateWithInternalGpsDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve friends at this time. If this occurs again please contact support with Error ID: {0}.
        /// </summary>
        public static string Text_Error_UnableToRetrieveFriends {
            get {
                return ResourceManager.GetString("Text_Error_UnableToRetrieveFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving you current location. If this occurs again please contact support with Error ID: {0}.
        /// </summary>
        public static string Text_Error_UnableToRetrieveLocation {
            get {
                return ResourceManager.GetString("Text_Error_UnableToRetrieveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle could not be saved. If this occurs again please contact support with Error ID: {0}.
        /// </summary>
        public static string Text_Error_UnableToSaveVehicle {
            get {
                return ResourceManager.GetString("Text_Error_UnableToSaveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload your best lap to server at this time. Track Timer will try again later or contact support with Error ID: {0}.
        /// </summary>
        public static string Text_Error_UnableToUploadBestLapToServer {
            get {
                return ResourceManager.GetString("Text_Error_UnableToUploadBestLapToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload track to server at this time. Please try again later or contact support with Error ID: {0}.
        /// </summary>
        public static string Text_Error_UnableToUploadTrackToServer {
            get {
                return ResourceManager.GetString("Text_Error_UnableToUploadTrackToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-upload sessions.
        /// </summary>
        public static string Text_Field_AutouploadSessions {
            get {
                return ResourceManager.GetString("Text_Field_AutouploadSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera password.
        /// </summary>
        public static string Text_Field_CameraPassword {
            get {
                return ResourceManager.GetString("Text_Field_CameraPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end latitude.
        /// </summary>
        public static string Text_Field_EndLatitude {
            get {
                return ResourceManager.GetString("Text_Field_EndLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end longitude.
        /// </summary>
        public static string Text_Field_EndLongitude {
            get {
                return ResourceManager.GetString("Text_Field_EndLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gps device.
        /// </summary>
        public static string Text_Field_GpsDeviceName {
            get {
                return ResourceManager.GetString("Text_Field_GpsDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heading.
        /// </summary>
        public static string Text_Field_Heading {
            get {
                return ResourceManager.GetString("Text_Field_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to official lap.
        /// </summary>
        public static string Text_Field_IsOfficialLap {
            get {
                return ResourceManager.GetString("Text_Field_IsOfficialLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        public static string Text_Field_Length {
            get {
                return ResourceManager.GetString("Text_Field_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow location access.
        /// </summary>
        public static string Text_Field_LocationConsent {
            get {
                return ResourceManager.GetString("Text_Field_LocationConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum speed.
        /// </summary>
        public static string Text_Field_MaximumSpeed {
            get {
                return ResourceManager.GetString("Text_Field_MaximumSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent precipitation.
        /// </summary>
        public static string Text_Field_PreviousHourPrecipitation {
            get {
                return ResourceManager.GetString("Text_Field_PreviousHourPrecipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recalculate sector line.
        /// </summary>
        public static string Text_Field_RecalculateSectorLine {
            get {
                return ResourceManager.GetString("Text_Field_RecalculateSectorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peak &amp; apex speeds.
        /// </summary>
        public static string Text_Field_ShowApexes {
            get {
                return ResourceManager.GetString("Text_Field_ShowApexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arial imagery.
        /// </summary>
        public static string Text_Field_ShowArialPhotography {
            get {
                return ResourceManager.GetString("Text_Field_ShowArialPhotography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show unofficial tracks.
        /// </summary>
        public static string Text_Field_ShowUnofficialTracks {
            get {
                return ResourceManager.GetString("Text_Field_ShowUnofficialTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive integration.
        /// </summary>
        public static string Text_Field_SkyDriveIntegration {
            get {
                return ResourceManager.GetString("Text_Field_SkyDriveIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start camera with timing.
        /// </summary>
        public static string Text_Field_StartCameraWithTiming {
            get {
                return ResourceManager.GetString("Text_Field_StartCameraWithTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish line.
        /// </summary>
        public static string Text_Field_StartFinishLine {
            get {
                return ResourceManager.GetString("Text_Field_StartFinishLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start latitude.
        /// </summary>
        public static string Text_Field_StartLatitude {
            get {
                return ResourceManager.GetString("Text_Field_StartLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start longitude.
        /// </summary>
        public static string Text_Field_StartLongitude {
            get {
                return ResourceManager.GetString("Text_Field_StartLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timestamp.
        /// </summary>
        public static string Text_Field_Timestamp {
            get {
                return ResourceManager.GetString("Text_Field_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day&apos;s precipitation.
        /// </summary>
        public static string Text_Field_TotalDayPrecipitation {
            get {
                return ResourceManager.GetString("Text_Field_TotalDayPrecipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background image.
        /// </summary>
        public static string Text_Field_TrackBackgroundImage {
            get {
                return ResourceManager.GetString("Text_Field_TrackBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string Text_Field_TrackDescription {
            get {
                return ResourceManager.GetString("Text_Field_TrackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        public static string Text_Field_TrackLength {
            get {
                return ResourceManager.GetString("Text_Field_TrackLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Text_Field_TrackName {
            get {
                return ResourceManager.GetString("Text_Field_TrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to units.
        /// </summary>
        public static string Text_Field_UnitType {
            get {
                return ResourceManager.GetString("Text_Field_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imperial.
        /// </summary>
        public static string Text_Field_UnitType_Imperial {
            get {
                return ResourceManager.GetString("Text_Field_UnitType_Imperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metric.
        /// </summary>
        public static string Text_Field_UnitType_Metric {
            get {
                return ResourceManager.GetString("Text_Field_UnitType_Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload over WiFi only.
        /// </summary>
        public static string Text_Field_UploadSessionsOverWiFiOnly {
            get {
                return ResourceManager.GetString("Text_Field_UploadSessionsOverWiFiOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string Text_Field_Version {
            get {
                return ResourceManager.GetString("Text_Field_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weather.
        /// </summary>
        public static string Text_Field_WeatherConditions {
            get {
                return ResourceManager.GetString("Text_Field_WeatherConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wind.
        /// </summary>
        public static string Text_Field_Wind {
            get {
                return ResourceManager.GetString("Text_Field_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        public static string Text_FieldHeading_VehicleClass {
            get {
                return ResourceManager.GetString("Text_FieldHeading_VehicleClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to make.
        /// </summary>
        public static string Text_FieldHeading_VehicleMake {
            get {
                return ResourceManager.GetString("Text_FieldHeading_VehicleMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model.
        /// </summary>
        public static string Text_FieldHeading_VehicleModel {
            get {
                return ResourceManager.GetString("Text_FieldHeading_VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authenticating.
        /// </summary>
        public static string Text_LoadingStatus_Authenticating {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating friend request.
        /// </summary>
        public static string Text_LoadingStatus_CreatingFriendRequest {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_CreatingFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating session.
        /// </summary>
        public static string Text_LoadingStatus_CreatingSession {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_CreatingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting session.
        /// </summary>
        public static string Text_LoadingStatus_DeletingSession {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_DeletingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finding closest circuit.
        /// </summary>
        public static string Text_LoadingStatus_FindingClosestCircuit {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_FindingClosestCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identifying best lap.
        /// </summary>
        public static string Text_LoadingStatus_IdentifyingBestLap {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_IdentifyingBestLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading activity feed.
        /// </summary>
        public static string Text_LoadingStatus_LoadingActivityFeed {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_LoadingActivityFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading best lap time.
        /// </summary>
        public static string Text_LoadingStatus_LoadingBestLapTime {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_LoadingBestLapTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading circuit.
        /// </summary>
        public static string Text_LoadingStatus_LoadingCircuit {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_LoadingCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading lap history.
        /// </summary>
        public static string Text_LoadingStatus_LoadingLapHistory {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_LoadingLapHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading session.
        /// </summary>
        public static string Text_LoadingStatus_LoadingSession {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_LoadingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading Settings.
        /// </summary>
        public static string Text_LoadingStatus_LoadingSettings {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading track Leaderboard.
        /// </summary>
        public static string Text_LoadingStatus_LoadingTrackLeaderboard {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_LoadingTrackLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registering best lap time.
        /// </summary>
        public static string Text_LoadingStatus_RegisteringBestLapTime {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_RegisteringBestLapTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renaming track file.
        /// </summary>
        public static string Text_LoadingStatus_RenamingTrackFile {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_RenamingTrackFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renaming track session files.
        /// </summary>
        public static string Text_LoadingStatus_RenamingTrackSessionFiles {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_RenamingTrackSessionFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving weather conditions.
        /// </summary>
        public static string Text_LoadingStatus_RetrievingWeatherConditions {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_RetrievingWeatherConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saving session.
        /// </summary>
        public static string Text_LoadingStatus_SavingSessionToPhone {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_SavingSessionToPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading session to OneDrive.
        /// </summary>
        public static string Text_LoadingStatus_SavingSessionToSkyDrive {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_SavingSessionToSkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server unavailable.
        /// </summary>
        public static string Text_LoadingStatus_ServerUnavailable {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting GPS.
        /// </summary>
        public static string Text_LoadingStatus_StartingGps {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_StartingGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating track cache.
        /// </summary>
        public static string Text_LoadingStatus_UpdatingTrackCache {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_UpdatingTrackCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading track.
        /// </summary>
        public static string Text_LoadingStatus_UploadingTrack {
            get {
                return ResourceManager.GetString("Text_LoadingStatus_UploadingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +/-.
        /// </summary>
        public static string Text_TableHeading_BestLapDifferenceTime {
            get {
                return ResourceManager.GetString("Text_TableHeading_BestLapDifferenceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Text_TableHeading_LapNumber {
            get {
                return ResourceManager.GetString("Text_TableHeading_LapNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lap time.
        /// </summary>
        public static string Text_TableHeading_LapTime {
            get {
                return ResourceManager.GetString("Text_TableHeading_LapTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to split time.
        /// </summary>
        public static string Text_TableHeading_SplitTime {
            get {
                return ResourceManager.GetString("Text_TableHeading_SplitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 10 Upgrade.
        /// </summary>
        public static string Text_Title_RequestUpgradeRegistration {
            get {
                return ResourceManager.GetString("Text_Title_RequestUpgradeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timing stopped.
        /// </summary>
        public static string Text_Toast_Content_TimingStopped {
            get {
                return ResourceManager.GetString("Text_Toast_Content_TimingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timing stopped - low battery.
        /// </summary>
        public static string Text_Toast_Content_TimingStoppedLowBattery {
            get {
                return ResourceManager.GetString("Text_Toast_Content_TimingStoppedLowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timing stopped - cannot access resources.
        /// </summary>
        public static string Text_Toast_Content_TimingStoppedLowResources {
            get {
                return ResourceManager.GetString("Text_Toast_Content_TimingStoppedLowResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Timer.
        /// </summary>
        public static string Text_Toast_Title {
            get {
                return ResourceManager.GetString("Text_Toast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        public static string Text_Toggle_Off {
            get {
                return ResourceManager.GetString("Text_Toggle_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string Text_Toggle_On {
            get {
                return ResourceManager.GetString("Text_Toggle_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track settings.
        /// </summary>
        public static string Text_TrackSettings {
            get {
                return ResourceManager.GetString("Text_TrackSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string Text_Unit_Degrees {
            get {
                return ResourceManager.GetString("Text_Unit_Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string Text_Unit_DegreesCentigrade {
            get {
                return ResourceManager.GetString("Text_Unit_DegreesCentigrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F.
        /// </summary>
        public static string Text_Unit_DegreesFarenheit {
            get {
                return ResourceManager.GetString("Text_Unit_DegreesFarenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXT GPS.
        /// </summary>
        public static string Text_Unit_ExternalGps {
            get {
                return ResourceManager.GetString("Text_Unit_ExternalGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G&apos;s.
        /// </summary>
        public static string Text_Unit_GForce {
            get {
                return ResourceManager.GetString("Text_Unit_GForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPH.
        /// </summary>
        public static string Text_Unit_ImperialSpeed {
            get {
                return ResourceManager.GetString("Text_Unit_ImperialSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        public static string Text_Unit_Inches {
            get {
                return ResourceManager.GetString("Text_Unit_Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        public static string Text_Unit_InternalGps {
            get {
                return ResourceManager.GetString("Text_Unit_InternalGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string Text_Unit_Kilometres {
            get {
                return ResourceManager.GetString("Text_Unit_Kilometres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laps.
        /// </summary>
        public static string Text_Unit_Laps {
            get {
                return ResourceManager.GetString("Text_Unit_Laps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km/h.
        /// </summary>
        public static string Text_Unit_MetricSpeed {
            get {
                return ResourceManager.GetString("Text_Unit_MetricSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string Text_Unit_Miles {
            get {
                return ResourceManager.GetString("Text_Unit_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string Text_Unit_Millimetres {
            get {
                return ResourceManager.GetString("Text_Unit_Millimetres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Timer.
        /// </summary>
        public static string Title_Application {
            get {
                return ResourceManager.GetString("Title_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add friend.
        /// </summary>
        public static string Title_Page_AddFriend {
            get {
                return ResourceManager.GetString("Title_Page_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicle.
        /// </summary>
        public static string Title_Page_AddVehicle {
            get {
                return ResourceManager.GetString("Title_Page_AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploads.
        /// </summary>
        public static string Title_Page_BackgroundUploads {
            get {
                return ResourceManager.GetString("Title_Page_BackgroundUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose degree.
        /// </summary>
        public static string Title_Page_ChooseDegree {
            get {
                return ResourceManager.GetString("Title_Page_ChooseDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit sector.
        /// </summary>
        public static string Title_Page_EditSector {
            get {
                return ResourceManager.GetString("Title_Page_EditSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit track.
        /// </summary>
        public static string Title_Page_EditTrack {
            get {
                return ResourceManager.GetString("Title_Page_EditTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lap detail.
        /// </summary>
        public static string Title_Page_LapDetail {
            get {
                return ResourceManager.GetString("Title_Page_LapDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage friends.
        /// </summary>
        public static string Title_Page_ManageFriends {
            get {
                return ResourceManager.GetString("Title_Page_ManageFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploads.
        /// </summary>
        public static string Title_Page_PendingUploads {
            get {
                return ResourceManager.GetString("Title_Page_PendingUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to session detail.
        /// </summary>
        public static string Title_Page_SessionHistory {
            get {
                return ResourceManager.GetString("Title_Page_SessionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Title_Page_Settings {
            get {
                return ResourceManager.GetString("Title_Page_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks.
        /// </summary>
        public static string Title_Page_Tracks {
            get {
                return ResourceManager.GetString("Title_Page_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop timing.
        /// </summary>
        public static string Title_Prompt_CancelTiming {
            get {
                return ResourceManager.GetString("Title_Prompt_CancelTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete local sessions.
        /// </summary>
        public static string Title_Prompt_DeleteAllLocalSessions {
            get {
                return ResourceManager.GetString("Title_Prompt_DeleteAllLocalSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete session.
        /// </summary>
        public static string Title_Prompt_DeleteSession {
            get {
                return ResourceManager.GetString("Title_Prompt_DeleteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete track.
        /// </summary>
        public static string Title_Prompt_DeleteTrack {
            get {
                return ResourceManager.GetString("Title_Prompt_DeleteTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete track cache.
        /// </summary>
        public static string Title_Prompt_DeleteTrackCache {
            get {
                return ResourceManager.GetString("Title_Prompt_DeleteTrackCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string Title_Prompt_Location {
            get {
                return ResourceManager.GetString("Title_Prompt_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string Title_Prompt_MustAuthenticate {
            get {
                return ResourceManager.GetString("Title_Prompt_MustAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Title_Section_Account {
            get {
                return ResourceManager.GetString("Title_Section_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends activity.
        /// </summary>
        public static string Title_Section_Activity {
            get {
                return ResourceManager.GetString("Title_Section_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        public static string Title_Section_Camera {
            get {
                return ResourceManager.GetString("Title_Section_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits.
        /// </summary>
        public static string Title_Section_Credits {
            get {
                return ResourceManager.GetString("Title_Section_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string Title_Section_Details {
            get {
                return ResourceManager.GetString("Title_Section_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requests.
        /// </summary>
        public static string Title_Section_FriendRequests {
            get {
                return ResourceManager.GetString("Title_Section_FriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string Title_Section_Friends {
            get {
                return ResourceManager.GetString("Title_Section_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string Title_Section_General {
            get {
                return ResourceManager.GetString("Title_Section_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        public static string Title_Section_Gps {
            get {
                return ResourceManager.GetString("Title_Section_Gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string Title_Section_LapDetails {
            get {
                return ResourceManager.GetString("Title_Section_LapDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to laps.
        /// </summary>
        public static string Title_Section_Laps {
            get {
                return ResourceManager.GetString("Title_Section_Laps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaderboard.
        /// </summary>
        public static string Title_Section_Leaderboard {
            get {
                return ResourceManager.GetString("Title_Section_Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string Title_Section_Map {
            get {
                return ResourceManager.GetString("Title_Section_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string Title_Section_Notes {
            get {
                return ResourceManager.GetString("Title_Section_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sectors.
        /// </summary>
        public static string Title_Section_Sectors {
            get {
                return ResourceManager.GetString("Title_Section_Sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sector splits.
        /// </summary>
        public static string Title_Section_SectorSplits {
            get {
                return ResourceManager.GetString("Title_Section_SectorSplits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to session history.
        /// </summary>
        public static string Title_Section_SessionHistory {
            get {
                return ResourceManager.GetString("Title_Section_SessionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        public static string Title_Section_Support {
            get {
                return ResourceManager.GetString("Title_Section_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string Title_Section_TrackDescription {
            get {
                return ResourceManager.GetString("Title_Section_TrackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicles.
        /// </summary>
        public static string Title_Section_Vehicles {
            get {
                return ResourceManager.GetString("Title_Section_Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        public static string Title_SubHeading_TrackLength {
            get {
                return ResourceManager.GetString("Title_SubHeading_TrackLength", resourceCulture);
            }
        }
    }
}
